// src/types/audit.ts
export type AuditActionType =
  | 'CASE_VIEWED' | 'CASE_FIELD_UPDATED'
  | 'TASK_COMPLETED' | 'TASK_ESCALATED'
  | 'DOCUMENT_UPLOADED' | 'DOCUMENT_VIEWED'
  | 'HTS_OVERRIDDEN' | 'OFAC_REVIEW_COMPLETED'
  | 'DUTY_SAVINGS_DECIDED' | 'AUDIT_EXPORTED'
  | 'SLA_ACKNOWLEDGED';
